import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "./layout.module.css";

export default function Layout({ children, ts = "", id = "", isFallback }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {id && ts ? "Back" : "Welcome"} to{" "}
          <Link href="/">
            <a>{id && ts ? "root page" : "ISR Testing!"}</a>
          </Link>
        </h1>

        <p className={styles.description}>
          {isFallback ? "Generating id..." : id ? `ID : ${id}` : null}
          <code className={styles.code}>{ts ? ts : "Click on a card"}</code>
        </p>

        <div className={styles.grid}>{children}</div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
